### ISSUE TITLE
isElementNode does not enforce `children` property

### ISSUE THREAD

**Issue by e1himself** [prezly/slate#1]
Hi! 

I have noticed that `isElementNode` does not enforce the `children` property to be defined on an object:

https://github.com/prezly/slate/blob/31a471e923a3c99ac5d2aa57535c42bc8949f0fd/packages/slate-types/src/nodes/ElementNode.ts#L10-L12

Is this intentional?

Thanks!

**Comment by kamilmielnik** [comment]
> Is this intentional?

Checking `children` was indeed unintentionally missing. Thank you for the report!

Fixed by https://github.com/prezly/slate/pull/2
