### ISSUE TITLE
Module not found: Can't resolve 'slate'

### ISSUE THREAD

**Issue by pablopunk** [prezly/slate#11]
On nextjs project:

```bash
$ npm i @prezly/slate-renderer@latest @prezly/slate-types@latest
$ npm run dev
```

![Captura de pantalla 2021-03-24 a las 10 18 10](https://user-images.githubusercontent.com/4324982/112285111-3d7e6080-8c8a-11eb-94fe-57979119c90b.png)

Problem is here: [packages/slate-types/src/nodes/Fragment.ts#L1](https://github.com/prezly/slate/blob/master/packages/slate-types/src/nodes/Fragment.ts#L1)

**Comment by kamilmielnik** [comment]
@pablopunk please try `@prezly/slate-renderer@0.1.0` - https://github.com/prezly/slate/commit/ab1e0df4045039e7b2041fe2821673dfa37440a9 should have fixed it.

If that didn't fix it, please provide steps to reproduce :pray:

**Comment by pablopunk** [comment]
@kamilmielnik I'm afraid it didn't fix it :(

Steps:

```bash
git clone git@github.com:prezly/website-nextjs.git
cd website-nextjs
npm i
npm i @prezly/slate-renderer@0.1.0 @prezly/slate-types@0.1.0
npm run dev
```

Manually installing `slate` with `npm i slate` solves the issue but I don't think we should install slate if we're not using it.

**Comment by kamilmielnik** [comment]
> Manually installing slate with npm i slate solves the issue

Great! That's exactly what I had in mind.

> but I don't think we should install slate if we're not using it.

`slate` is a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) of `@prezly/slate-renderer` :man_shrugging: 

We could do the same thing as `react-use` did (issue: https://github.com/streamich/react-use/issues/384, PR: https://github.com/streamich/react-use/pull/472/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R31-R65) but I find that more complex than installing a peer dependency.

----

Anyway, I consider the issue (i.e. `slate` was not listed as `peerDependency`) solved.

If you have an idea/suggestion for improvement here that you feel strongly about, please create a separate issue.
