### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by zajhar** [prezly/slate#128]
Hey
While following usage example I ran into a exports problem. 

`Attempted import error: 'Lists' is not exported from '@prezly/slate-lists'.`

Error is present only with latest version. 
"@prezly/slate-lists": "0.1.0-alpha.25", Used in example works well for me. 
What can I do with it? 
Thanks!

**Comment by zajhar** [comment]
Looks like the issue was that webpack was not handling .mjs files. If we use proper package.json is still a requirement to use this format?

**Comment by e1himself** [comment]
Hi @zajhar 

Please note that the `slate-lists` package was refactored in [v0.32](https://github.com/prezly/slate/releases/tag/v0.32.0) (released on April 21, 2022).

As of now it doesn't export `Lists`, but uses a slightly different approach (though porting code to the new version is easy).

Please take a look at the updated README docs:
 https://github.com/prezly/slate/blob/master/packages/slate-lists/README.md

And the respective PR: https://github.com/prezly/slate/pull/148

**Comment by e1himself** [comment]
I'm going to close this issue, but if you still have problems with the import, please comment here. I'll reopen it back.
