### ISSUE TITLE
Module "slate" declare conflict

### ISSUE THREAD

**Issue by tilemoon** [prezly/slate#132]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/37775224/157862010-19674e55-f424-4697-9a35-76f6a5deeee7.png">

When i import something from @prezy/slate-lists, there will be an error below.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/37775224/157862334-19f90db7-5cf6-4c04-87df-30bbc94eeadb.png">

**Comment by wildf1r3** [comment]
Hi @tilemoon this seems to be the same problem as in issue #49 , im also waiting for an answer from the author on this regard, if you find any suitable solution other  than just forking and fixing it yourself, please let me know!

Thanks a bunch!
