### ISSUE TITLE
Ordered list becomes unordered on tab

### ISSUE THREAD

**Issue by dmathijs** [prezly/slate#365]
![eNOnvpfRHK](https://user-images.githubusercontent.com/4018247/209941656-09093a28-3b5c-4c31-baf1-600c6e48c8ab.gif)

I've found that tabbing in an ordered list makes the child unordered [by default](https://github.com/prezly/slate/blob/4c32ca38059dac643dac139c7f1a7d48af7a196e/packages/slate-lists/src/transformations/increaseDepth.ts#L14), is this a deliberate design decision?

**Comment by e1himself** [comment]
Hi @dmathijs

I don't think it really was a deliberate design decision. It just happened to be the default behaviour in our implementation :) 

Would you expect it to inherit the parent list type by default? It shouldn't be difficult to modify this behavior.

**Comment by amorphedstar** [comment]
@e1himself I think it would be good if the behavior were similar to Google Docs, where ordered lists indent to ordered lists and unordered lists indent to unordered lists by default.

**Comment by NourIM** [comment]
Hi @e1himself 

I want to raise this point as well! The order list should stay the order list when creating nested children. 
Can we get a resolution soon, please?

And thanks for the great package! :)

<img width="415" alt="Screenshot 2023-02-27 at 16 43 47" src="https://user-images.githubusercontent.com/14943545/221625800-59bf3e38-2c1c-4bbb-ba28-9727dd6a421b.png">

**Comment by NourIM** [comment]
I've updated types to the HTML element, and it worked for me. 
`enum Type {
  PARAGRAPH = 'paragraph',
  ORDERED_LIST = 'ol',
  UNORDERED_LIST = 'ul',
  LIST_ITEM = 'li',
  LIST_ITEM_TEXT = 'list-item-text'
}`
<img width="505" alt="Screenshot 2023-03-02 at 14 52 19" src="https://user-images.githubusercontent.com/14943545/222462956-fa5ce18f-691f-40f7-8e8b-b9e9f30f75cb.png">

**Comment by e1himself** [comment]
Related/duplicate: #391
