### ISSUE TITLE
Figured out why Ordered Lists become unordered on tab

### ISSUE THREAD

**Issue by leo-petrucci** [prezly/slate#391]
There's a couple of issues open about ordered lists being switched to unordered when tab is pressed. As mentioned by the maintainers the code is set up to inherit the type of the containing list, but there's a small issue that prevents that from working correctly.

I decided to copy the source to my own project to figure it out and the issue resides within types:

https://github.com/prezly/slate/blob/83d9b3901a899dadaffc370b7216bf7ad7218a00/packages/slate-lists/src/types.ts#L4

Increasing depth checks that these strings equal the same type as the list type from the editor. If your editor uses these same strings (`ol` and `ul`) then everything will work just fine. However if you've customised your node types (say you have `ordered_list` and `unordered_list`), then it won't find the correct match and just default to `unordered`.

Hope this helps someone, not familiar enough with the codebase to attempt a PR, sorry!

**Comment by alexvance0** [comment]
I just found this too! I hope to make an update sometime soon, but this is what worked for me:

Since the README says to include the `ORDERED_LIST = 'ordered-list',` and `UNORDERED_LIST = 'unordered-list',` values, I added a transformer object to conform to the `types.ts` types

    export const ListTypeTransformer = {
        ol: SlateElementType.ORDERED_LIST,
        ul: SlateElementType.UNORDERED_LIST,
    };

Then, I updated the `isListNode` function that the README says to use to be

    isListNode(node: SlateNode, type?: ListType) {
        if (type) {
            const transformedType = ListTypeTransformer[type]; // transforms the 'ordered-list' into 'ol' and same for 'ul'
            return SlateElement.isElementType(node, transformedType);
        }
        return (
            SlateElement.isElementType(node, SlateElementType.ORDERED_LIST) ||
            SlateElement.isElementType(node, SlateElementType.UNORDERED_LIST)
        );
    },

**Comment by vancy-pants** [comment]
I just found this too! I hope to make an update sometime soon, but this is what worked for me:

Since the README says to include the `ORDERED_LIST = 'ordered-list',` and `UNORDERED_LIST = 'unordered-list',` values, I added a transformer object to conform to the `types.ts` types

    export const ListTypeTransformer = {
        ol: SlateElementType.ORDERED_LIST,
        ul: SlateElementType.UNORDERED_LIST,
    };

Then, I updated the `isListNode` function that the README says to use to be

    isListNode(node: SlateNode, type?: ListType) {
        if (type) {
            const transformedType = ListTypeTransformer[type]; // transforms the 'ordered-list' into 'ol' and same for 'ul'
            return SlateElement.isElementType(node, transformedType);
        }
        return (
            SlateElement.isElementType(node, SlateElementType.ORDERED_LIST) ||
            SlateElement.isElementType(node, SlateElementType.UNORDERED_LIST)
        );
    },

**Comment by e1himself** [comment]
@leo-petrucci 

> Increasing depth checks that these strings equal the same type as the list type from the editor. If your editor uses these same strings (ol and ul) then everything will work just fine. However if you've customised your node types (say you have ordered_list and unordered_list), then it won't find the correct match and just default to unordered.

So, as far as I understand this correctly, the bug is in the implementation suggested in the README, right?

```diff
 isListNode(node: Node, type?: ListType) {
-    if (type) {
-        return Element.isElementType(node, type);
-    }
+    if (type === ListType.ORDERED) {
+       return Element.isElementType(node, Type.ORDERED_LIST);
+    }
+    if (type === ListType.UNORDERED) {
+       return Element.isElementType(node, Type.UNORDERED_LIST);
+    }
     return (
         Element.isElementType(node, Type.ORDERED_LIST) ||
         Element.isElementType(node, Type.UNORDERED_LIST)
     );
 },
```

Once you fix the `isListNode` function in your schema, it should work as expected. Right?

**Comment by e1himself** [comment]
@leo-petrucci No worries. This is mostly on our team for not replying to this issue sooner.
