### ISSUE TITLE
How would I add additional functionality to the withListsPlugin?

### ISSUE THREAD

**Issue by peter-stuart-turner** [prezly/slate#396]
I would like to add a function that is able to 'split' a list (unordered/ordered) into two separate lists of same type, in event someone [drags and] drops a non-list element in between list-items (like an image)

I'm struggling to know 'where to put' that code without making another lists plugin, could you please advise?

Great library! Loving it, thanks a bunch.

**Comment by peter-stuart-turner** [comment]
^ also may be my lack of slate knowledge - but any advice would be much appreciated, would definitely like to be a long-term user and eventually a contributor of this slate plugin

**Comment by e1himself** [comment]
Hi @peter-stuart-turner!

> I would like to add a function that is able to 'split' a list (unordered/ordered) into two separate lists of same type, in event someone [drags and] drops a non-list element in between list-items (like an image)

There is slight problem in _just_ splitting a list into two. The `@prezly/slate-lists` plugin has a built-in normalization to automatically merge lists of the same type that follow one after another.

However, your use-case sounds more like a job for normalization. I'd look into overriding editor normalization to automatically lift non-support list-item children (like an image node). There's even a stock transformation function available: [`Transforms.liftNodes()`](https://docs.slatejs.org/api/transforms#transforms.liftnodes-editor-editor-options).

- See https://docs.slatejs.org/api/transforms#transforms.liftnodes-editor-editor-options
- https://docs.slatejs.org/concepts/11-normalizing

And also, my apologies for the delayed response.

**Comment by e1himself** [comment]
Closing this for now. Feel free to comment to reopen this discussion. Cheers :v:

**Comment by peter-stuart-turner** [comment]
Many thanks! I will go with that approach
