### ISSUE TITLE
slate-lists: Cannot customize types

### ISSUE THREAD

**Issue by greypants** [prezly/slate#49]
Because slate custom types are declared here:
https://github.com/prezly/slate/blob/master/packages/slate-lists/src/index.ts#L6-L12

I'm having trouble creating my own custom types:

```ts
Subsequent property declarations must have the same type.  Property 'Text' must be of type 'TextNode', but here has type 'CustomText'.ts(2717)
index.d.ts(9, 9): 'Text' was also declared here.
(property) CustomTypes.Text: TextNode
```

![image](https://user-images.githubusercontent.com/647549/143132925-90776768-cef3-4ee5-8151-7353c513adf7.png)

What's the right way to customize types when using this plugin? Maybe that module declaration shouldn't be in the package?

**Comment by e1himself** [comment]
Hi @greypants!

You are totally right that at the current state the type system is not really extensible. It's on our ToDo list to have the package less hard-coded on the supported node types. One step towards that direction we already did with #36, but there's more work to be done.

Can you please describe your use case so I better understand what you're trying to achieve?

Thanks!

**Comment by greypants** [comment]
Sure - I'm building a Slate-based editor with custom features and was following the TypeScript section of their docs here: https://docs.slatejs.org/concepts/12-typescript#best-practices-for-element-and-text-types

For example, here's my `Text` definition: 

```tsx
export interface FormattedText {
  text: string;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  fontSize?: number;
}

export interface EmptyText {
  text: string;
}

export type CustomText = FormattedText | EmptyText;

declare module "slate" {
  interface CustomTypes {
    // Can't override - already defined in @prezly/slate-lists 
    Text: CustomText;
  }
}
```

I had to comment out the `declare module "slate"` block after adding the `@prezly/slate-lists` library.  So now all the types are being inherited from this package, rather from my own definitions.

<img width="632" alt="Screen Shot 2021-11-29 at 8 04 43 PM" src="https://user-images.githubusercontent.com/647549/143966913-9300bd92-9ada-44e6-969b-b40c2a041f69.png">

If the plugin requires some base types, would it make sense to export those base types and have consumers extend them?

```tsx
import { CustomText as PrezlyCustomText } from "@prezly/slate-lists";

...
type CustomText = PrezlyCustomText & FormattedText

declare module "slate" {
  interface CustomTypes {
    Text: CustomText;
  }
}
```

My instinct says that a plugin shouldn't `declare module "slate"` - that's something that the editor code itself should do, right?

**Comment by greypants** [comment]
Also - THANK YOU FOR OPEN SOURCING THIS CODE! I was really struggling trying to get nested lists working. This plugin saved me days of work - the API is pretty perfect 👍🏽

**Comment by e1himself** [comment]
> My instinct says that a plugin shouldn't declare module "slate" - that's something that the editor code itself should do, right?

Yes, that's exactly what I had in mind :+1: 

I have been handed this package over last month and still didn't get to fixing this problem. Will try to address this next month before end of year.

**Comment by wildf1r3** [comment]
Hi @e1himself!

Are there any news regarding this issue? I`m currently running into the same problem and i'd very much love to use your slate-list package, as it is very well written and documented!

Thanks a lot in advance!

**Comment by e1himself** [comment]
Hi @wildf1r3

This problem did not get much attention in the past months. 
However, I have something in the works now. I will be posting updates in the upcoming days.

Thanks for the reminde.

**Comment by wildf1r3** [comment]
Thanks for the update! Im looking forward to your work!

**Comment by e1himself** [comment]
@wildf1r3 @greypants Please take a look at this PR I have here: #148. The plan is to merge and release it somewhere next week.

**Comment by greypants** [comment]
I'm super late, but finally got around to upgrading. Works great! Thanks so much 👍🏽

**Comment by e1himself** [comment]
@greypants 

Great to hear! Thanks for reporting back. :+1: 

Happy coding :wink:
