### ISSUE TITLE
Slate Lists, painfully slow on larger documents

### ISSUE THREAD

**Issue by LukasMappdev** [prezly/slate#524]
Hello everyone, I am quite new to React. I recently wanted to include a rich text editor in my web app and used slate js. I then came across your work and really like slate-lists. However if I run larger documents through my editor it suddenly runs painfully slow. The vanilla version of slate js does not cause this problem. I just wanted to know, whether this is known or my implementation is wrong. I can provide code snippets if it helps.

I could already figure out that the part which slows down the app is the component onKeyDown that I imported from your package

Sorry, if I dont follow yet best practises for issue requests, as I am quite new to this.

Best,
Lukas

**Comment by e1himself** [comment]
Hey @LukasMappdev 

Thank you for reporting this. :+1: 

>  I can provide code snippets if it helps.

Yeah, it's always a great idea to link to a sandbox where the issue can be reproduced, so we are sure we see it the way you see it. Please, go ahead :) 

Also, is the problem universal to all browsers, or a specific one? 

Thanks!

**Comment by LukasMappdev** [comment]
Thank you for your quick reply!

I built a simple example in a sandbox:
https://codesandbox.io/p/sandbox/simple-text-editor-demo-forked-x8cmkn

Note that this is of course a really big document but the difference in performance also starts to be noticed for much smaller documents. 

To test the difference in performance please remove line 320 in "simpletexteditor.jsx" , which is the onKeyDown function imported from slate-lists.

I really appreciate any feedback or tips you have concerning the performance. The issue took place in Google Chrome and Safari. I did not test other browsers.

Best,
Lukas

**Comment by LukasMappdev** [comment]
Hello,
I just wanted to kindly reach out and ask whether you have investigated this further and have an update.

Best,
Lukas
