### ISSUE TITLE
Demo breaks after specific combinations of nesting/unnesting operations

### ISSUE THREAD

**Issue by e1himself** [prezly/slate#8]
I've managed to break the Demo editor mentioned in #7.

I've only used `Tab` or `Shift-Tab` on my keyboard to nest/unnest specific portions of text.

![Знімок з 2021-02-17 14-48-07](https://user-images.githubusercontent.com/370680/108207212-1b943a00-7130-11eb-92eb-071366818380.png)

https://user-images.githubusercontent.com/370680/108207202-17681c80-7130-11eb-9a56-698b42723b35.mp4

---

Browser: Firefox 85.0.1 (64-bit) for Ubuntu

**Comment by kamilmielnik** [comment]
Thanks for the report!

I believe I've fixed it - I cannot reproduce it anymore. 

@e1himself can you please give it a try? :pray: 

https://codesandbox.io/s/prezlyslate-lists-demo-complete-example-h9xxi?file=/src/App.tsx

**Comment by e1himself** [comment]
Thanks @kamilmielnik!

It seems to be fixed now. 

Good job! :+1:
